### ISSUE TITLE
possible error in this paper

### ISSUE THREAD

**Issue by Gmrylbx** [FanzhenLiu/Awesome-Deep-Community-Detection#16]
Thank you for your contribution

However, i found  some possible error in this paper(A Comprehensive Survey on Community Detection with Deep Learning, TKDE 2021)

For example, in TABLE IX: Summary of real-world benchmark data sets, there is a data statistics as follows:
Twitter[16].     81306 1768149 216839 4065      [68], [94], [109], [115]

but in [115](Community-Centric Graph Convolutional Network for Unsupervised Community Detection, IJCAI 2020)
the 'Twitter' dataset only have 171 nodes,  maybe both datasets are from the same dataset, but I think it should be marked in the article.

**Comment by FanzhenLiu** [comment]
Thanks for your information and showing interests in our work. As you may know, this survey involved a tremendous amount of work. Regarding TABLE IX, [68], [94], and [109] study the most popular dataset of Twitter contributed by [16], while [115] studies another Twitter dataset with 171 nodes. In a limited space, it is impossible to give details on all 44 datasets used by nearly a hundred works. We aim to collect popular datasets and show the statistics of the popular example for datasets with the same name. If you have further confusion, please contact us by email (fanzhen.liu@hdr.mq.edu.au). We are happy to answer any further questions.
